apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shippingservice-2-allow-checkoutservice-2
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: checkoutservice-2
    ports:
    - port: 34213
  podSelector:
    matchLabels:
      app: shippingservice-2
