apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shippingservice-3-allow-frontend-2
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend-2
    ports:
    - port: 3148
  podSelector:
    matchLabels:
      app: shippingservice-3
