apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shippingservice-3-allow-checkoutservice-4
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: checkoutservice-4
    ports:
    - port: 3148
  podSelector:
    matchLabels:
      app: shippingservice-3
