apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shippingservice-4-allow-checkoutservice-7
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: checkoutservice-7
    ports:
    - port: 22812
  podSelector:
    matchLabels:
      app: shippingservice-4
