apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: productcatalogservice-7-allow-recommendationservice-0
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: recommendationservice-0
    ports:
    - port: 47981
  podSelector:
    matchLabels:
      app: productcatalogservice-7
