apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: emailservice-1-allow-checkoutservice-8
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: checkoutservice-8
    ports:
    - port: 24554
  podSelector:
    matchLabels:
      app: emailservice-1
