apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice-2
spec:
  ports:
  - name: grpc
    port: 60742
    targetPort: 60742
  selector:
    app: productcatalogservice-2
  type: ClusterIP
