apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice-5
spec:
  ports:
  - name: grpc
    port: 49178
    targetPort: 49178
  selector:
    app: productcatalogservice-5
  type: ClusterIP
