apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-6
spec:
  ports:
  - name: grpc
    port: 59822
    targetPort: 59822
  selector:
    app: recommendationservice-6
  type: ClusterIP
