apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: recommendationservice-5-allow-frontend-11
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend-11
    ports:
    - port: 49759
  podSelector:
    matchLabels:
      app: recommendationservice-5
