apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-1
spec:
  ports:
  - name: grpc
    port: 54251
    targetPort: 54251
  selector:
    app: recommendationservice-1
  type: ClusterIP
