apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: recommendationservice-6-allow-frontend-6
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend-6
    ports:
    - port: 59822
  podSelector:
    matchLabels:
      app: recommendationservice-6
