apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-3
spec:
  ports:
  - name: grpc
    port: 12154
    targetPort: 12154
  selector:
    app: recommendationservice-3
  type: ClusterIP
