apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: checkoutservice-3-allow-frontend-11
  namespace: attack-graphs
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend-11
    ports:
    - port: 19960
  podSelector:
    matchLabels:
      app: checkoutservice-3
