apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-11
spec:
  selector:
    matchLabels:
      app: frontend-11
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
      labels:
        app: frontend-11
    spec:
      containers:
      - env:
        - name: PORT
          value: '51722'
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice-4:47089
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice-6:10455
        - name: CART_SERVICE_ADDR
          value: cartservice-1:7070
        - name: RECOMMENDATION_SERVICE_ADDR
          value: recommendationservice-5:49759
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice-2:60320
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice-3:19960
        - name: AD_SERVICE_ADDR
          value: adservice-1:44978
        - name: ENABLE_PROFILER
          value: '0'
        image: gcr.io/google-samples/microservices-demo/frontend:v0.5.0
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-liveness-probe
            path: /_healthz
            port: 51722
          initialDelaySeconds: 0
        name: server
        ports:
        - containerPort: 51722
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-readiness-probe
            path: /_healthz
            port: 51722
          initialDelaySeconds: 0
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: default
